import { DarkModeOutlined, LightModeOutlined } from "@mui/icons-material";
import { Typography, AppBar, Toolbar, IconButton } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

// eslint-disable-next-line react/prop-types
const Home: NextPage = ({ toggleTheme, selectedTheme }: any) => {
  return (
    <div>
      <Head>
        <title>IMorad Resume </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppBar position="static" color="primary">
          <Toolbar>
            <Typography variant="h6" flexGrow={1}>
              Islam Morad
            </Typography>
            <IconButton aria-label="theme switch" onClick={toggleTheme}>
              {selectedTheme === "light" ? <DarkModeOutlined color="inherit" /> : <LightModeOutlined color="primary" />}
            </IconButton>
          </Toolbar>
        </AppBar>
        <Typography variant="h4 ">Hello World!</Typography>
      </main>
    </div>
  );
};

export default Home;
