on: [push]

jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: SFTP Push
              uses: zurb/sftp-upload-action@1.3
              with:
                    # username
                username: '${{ secrets.FTP_USERNAME }}'
                    # your sftp server
                host: '${{ secrets.FTP_SERVER }}'
                    # your sftp server port, default to 22
                port: '${{ secrets.FTP_PORT }}'
                    # you can copy private_key from your *.pem file, keep format
                password: '${{ secrets.FTP_PASSWORD }}'
                    # will put all file under this path
                localDir: './src'
                    # files will copy to under remote_path
                remoteDir: '/test_action/'
                dryRun: true
