on: [push]

jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: SFTP Push
              uses: datanomi/SFTP-Push@v.1.2.2.1h
              with:
                    # username
                username: '${{ secrets.FTP_USERNAME }}'
                    # your sftp server
                server: '${{ secrets.FTP_SERVER }}'
                    # your sftp server port, default to 22
                port: '${{ secrets.FTP_PORT }}'
                    # you can copy private_key from your *.pem file, keep format
                ssh_private_key: '${{ secrets.FTP_PASSWORD }}'
                    # will put all file under this path
                local_path: '/src/'
                    # files will copy to under remote_path
                remote_path: '/test_action/'
