on: [push]

jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: FTP Deploy
  # You may pin to the exact commit or the version.
  # uses: SamKirkland/FTP-Deploy-Action@1b21034a8decff23858a1721ca2c25b949b4bc78
              uses: SamKirkland/FTP-Deploy-Action@4.3.2
              with:
                # ftp server
                server: '${{ test_action.FTP_SERVER }}'
                # ftp username
                username: '${{ test_action.FTP_USERNAME }}'
                # ftp password
                password: '${{ test_action.FTP_PASSWORD }}'
                # Server port to connect to (read your web hosts docs)
                port: '${{ test_action.FTP_PORT }}'
                # protocol to deploy with - ftp, ftps, or ftps-legacy
                protocol: ftps
                # Folder to upload from, must end with trailing slash /
                local-dir: ./src/
                # Path to upload to on the server. Must end with trailing slash /
                server-dir: /test_action/
                timeout: 180000

           
